project_id = "wdkqzqcmqblzqglwjyqv"

[functions.chat]
verify_jwt = false

[functions.generate-cards]
verify_jwt = false

[functions.generate-pet-image]
verify_jwt = false

[functions.speaking]
verify_jwt = false

[functions.speaking-feedback]
verify_jwt = false

[functions.split-dialogue]
verify_jwt = false

[functions.analyze-text]
verify_jwt = false
